### ISSUE TITLE
Move this project to meow-edit organization

### ISSUE THREAD

**Issue by VitalyAnkh** [45mg/doom-meow-module#1]
Would you consider transferring this project to the meow-edit organization? This move could significantly improve discoverability for users seeking ways to integrate Meow with Doom Emacs.

The current [doom-meow](https://github.com/meow-edit/doom-meow) repository under meow-edit has been unmaintained for two years. Your project, on the other hand, is well-developed, and I believe it deserves wider adoption.

**Comment by 45mg** [comment]
I agree with this idea and would like to move forward with it.

Based on [the official guide](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#repository-transfers-and-organizations), I guess I need repo creation permissions in meow-edit to make the transfer.

Also, shall we rename this repo to `doom-meow`, if you're planning to replace that one? `doom-meow-module` is a bit too long IMO, and I only picked it to avoid confusion with your repo.

**Comment by VitalyAnkh** [comment]
We will invite you to the organization then you will have permission to create repos.

And I will rename and archive the old doom-meow repo, then you could rename it to that name.

Welcome to the meow developer community! :rocket: :rocket: :rocket:

**Comment by DogLooksGood** [comment]
Hey, @45mg . Invitation and rename have been done.
