### ISSUE TITLE
One minor problem in meow tutor

### ISSUE THREAD

**Issue by Rope-a-dope** [45mg/doom-meow-module#4]
On "MORE ON BEACON" part,  if we follow the instruction then you can see there is also a fake cursor in front of -->.  
And if we follow step 6, then the edits only apply to number 3.

![image](https://github.com/user-attachments/assets/303d98e3-3c8e-4dc0-8d36-01ecf3d957ec)

I had to type e to reduce selection, then edit, then just press G to cancel grab.  There is the same example here [Explanation - Ways to multiedit - The answer from Meow](https://github.com/meow-edit/meow/blob/master/EXPLANATION.org), but obviously there is no "-->" here.
![image](https://github.com/user-attachments/assets/a4295ce0-71c8-4e19-bbc5-acafa508af54)

**Comment by 45mg** [comment]
Issues not pertaining specifically to this module should be reported [upstream](https://github.com/meow-edit/meow/issues).
